FROM continuumio/anaconda3
MAINTAINER Billy Taj
RUN apt-get update
RUN apt-get install wget
RUN apt-get install unzip
RUN apt-get -y install g++
RUN apt-get -y install gcc
RUN apt-get -y install make
RUN apt-get -y install libz-dev
RUN apt-get -y install libbz2-dev
RUN apt-get -y install autoconf
RUN apt-get -y install build-essential
RUN apt-get -y install libboost-all-dev
RUN apt-get -y install flex
RUN apt-get -y install cmake
RUN apt-get -y install libncurses5-dev
RUN apt-get -y install liblzma-dev
RUN apt-get -y install perl
RUN conda update -n base conda -y
RUN conda install Biopython -y 
RUN conda install Pandas -y
RUN apt-get install openjdk-8-jre -y
RUN apt-get install openjdk-8-jdk -y
RUN echo "hello from custom dockerfile"
RUN echo "it's done"
WORKDIR /pipeline_tools

# Install PRIAM
RUN mkdir PRIAM_search
RUN wget http://priam.prabi.fr/utilities/PRIAM_search.jar
RUN mv PRIAM_search.jar PRIAM_search