FROM continuumio/anaconda3
MAINTAINER Billy Taj
RUN apt-get update
RUN apt-get install wget
RUN apt-get install unzip
RUN apt-get -y install g++
RUN apt-get -y install gcc
RUN apt-get -y install make
RUN apt-get -y install libz-dev
RUN apt-get -y install libbz2-dev
RUN apt-get -y install autoconf
RUN apt-get -y install build-essential
RUN apt-get -y install libboost-all-dev
RUN apt-get -y install flex
RUN apt-get -y install cmake
RUN apt-get -y install libncurses5-dev
RUN apt-get -y install liblzma-dev
RUN apt-get -y install perl
RUN conda update -n base conda -y
RUN conda install Biopython -y 
RUN conda install Pandas -y
RUN echo "hello from custom dockerfile"

WORKDIR /pipeline_tools


#----------------------------------------------------
# Install Centrifuge
RUN wget https://github.com/infphilo/centrifuge/archive/v1.0.3.tar.gz -O centrifuge.tar.gz
RUN tar --remove-files -xzvf centrifuge.tar.gz && rm centrifuge.tar.gz && mkdir /pipeline_tools/centrifuge
WORKDIR centrifuge-1.0.3
RUN make && mv centrifuge ../centrifuge && mv centrifuge-class ../centrifuge && mv centrifuge-kreport ../centrifuge && mv centrifuge-build ../centrifuge
WORKDIR /pipeline_tools
RUN rm -r centrifuge-1.0.3

#------------------------------------
# Install WEVOTE
RUN wget https://github.com/aametwally/WEVOTE/archive/master.zip -O wevote.zip
RUN unzip wevote.zip && rm wevote.zip
WORKDIR WEVOTE-master
RUN mkdir ../WEVOTE 
RUN ./install.sh && mkdir WEVOTE_db 
RUN mv bin/WEVOTE ../WEVOTE && mv downloadTaxonomyDB.sh ../WEVOTE && mkdir ../WEVOTE/WEVOTE_db && sh ../WEVOTE/downloadTaxonomyDB.sh ../WEVOTE/WEVOTE_db
WORKDIR /pipeline_tools
RUN rm -r WEVOTE-master